package com.model;

import com.model.base.BaseRoleRes;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleRes extends BaseRoleRes<RoleRes> {
	public static final RoleRes dao = new RoleRes();
}
