package com.model;

import com.auth.base.MyConstant;
import com.auth.util.Empty;
import com.auth.util.MD5Unit;
import com.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User();

	public boolean isRegisterUser(String username,String password){
		String md5 = MD5Unit.GetMD5Code(password) + MyConstant.MD5;
		md5 = MD5Unit.GetMD5Code(md5);
        String sql = "SELECT * FROM "+MyConstant.TABLE_PREFIX+"user WHERE user_username = ? AND user_pwd = ?";
		User user = dao.findFirst(sql,username,md5);
		return user!=null;
	}

	public User findUserByName(String username){
		String sql = "SELECT * FROM "+ MyConstant.TABLE_PREFIX+"user WHERE user_username = ? ";
		return dao.findFirst(sql,username);
	}

	public User getUser(String username,String password){
		if(Empty.isEmpty(username) || Empty.isEmpty(password)){
			return null;
		}
		String md5 = MD5Unit.GetMD5Code(password) + MyConstant.MD5;
		md5 = MD5Unit.GetMD5Code(md5);
		String sql = "SELECT * FROM "+MyConstant.TABLE_PREFIX+"user WHERE user_username = ? AND user_pwd = ?";
		return dao.findFirst(sql,username,md5);
	}




}
