package com.model;

import com.model.base.BaseUserApp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserApp extends BaseUserApp<UserApp> {
	public static final UserApp dao = new UserApp();
}
