package com.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRes<M extends BaseRes<M>> extends Model<M> implements IBean {

	public void setResId(String resId) {
		set("res_id", resId);
	}

	public String getResId() {
		return get("res_id");
	}

	public void setResPid(String resPid) {
		set("res_pid", resPid);
	}

	public String getResPid() {
		return get("res_pid");
	}

	public void setResName(String resName) {
		set("res_name", resName);
	}

	public String getResName() {
		return get("res_name");
	}

	public void setResUrl(String resUrl) {
		set("res_url", resUrl);
	}

	public String getResUrl() {
		return get("res_url");
	}

	public void setResIcon(String resIcon) {
		set("res_icon", resIcon);
	}

	public String getResIcon() {
		return get("res_icon");
	}

	public void setResSeq(String resSeq) {
		set("res_seq", resSeq);
	}

	public String getResSeq() {
		return get("res_seq");
	}

	public void setResType(String resType) {
		set("res_type", resType);
	}

	public String getResType() {
		return get("res_type");
	}

	public void setCreatedAt(String createdAt) {
		set("created_at", createdAt);
	}

	public String getCreatedAt() {
		return get("created_at");
	}

	public void setUpdatedAt(String updatedAt) {
		set("updated_at", updatedAt);
	}

	public String getUpdatedAt() {
		return get("updated_at");
	}
}
