package com.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRole<M extends BaseRole<M>> extends Model<M> implements IBean {

	public void setRoleId(String roleId) {
		set("role_id", roleId);
	}

	public String getRoleId() {
		return get("role_id");
	}

	public void setRoleName(String roleName) {
		set("role_name", roleName);
	}

	public String getRoleName() {
		return get("role_name");
	}

	public void setRoleDescription(String roleDescription) {
		set("role_description", roleDescription);
	}

	public String getRoleDescription() {
		return get("role_description");
	}

	public void setRoleIcon(String roleIcon) {
		set("role_icon", roleIcon);
	}

	public String getRoleIcon() {
		return get("role_icon");
	}

	public void setCreatedAt(String createdAt) {
		set("created_at", createdAt);
	}

	public String getCreatedAt() {
		return get("created_at");
	}

	public void setUpdatedAt(String updatedAt) {
		set("updated_at", updatedAt);
	}

	public String getUpdatedAt() {
		return get("updated_at");
	}

}
