package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}

	public java.lang.String getUserId() {
		return get("user_id");
	}

	public void setUserUsername(java.lang.String userUsername) {
		set("user_username", userUsername);
	}

	public java.lang.String getUserUsername() {
		return get("user_username");
	}

	public void setUserPwd(java.lang.String userPwd) {
		set("user_pwd", userPwd);
	}

	public java.lang.String getUserPwd() {
		return get("user_pwd");
	}

	public void setUserSlat(java.lang.String userSlat) {
		set("user_slat", userSlat);
	}

	public java.lang.String getUserSlat() {
		return get("user_slat");
	}

	public void setUserStatus(java.lang.String userStatus) {
		set("user_status", userStatus);
	}

	public java.lang.String getUserStatus() {
		return get("user_status");
	}

	public void setCreatedAt(java.lang.String createdAt) {
		set("created_at", createdAt);
	}

	public java.lang.String getCreatedAt() {
		return get("created_at");
	}

}
